### ISSUE TITLE
PersistentWindows dont remember my capture after reboot

### ISSUE THREAD

**Issue by dhaern** [kangyu-california/PersistentWindows#48]
I have 2x monitors connected by Displayport and using windows 10 Enterprise LTSC, I installed last 4.40 version and after I reboot persistentwindows dont remember the captured position and I cant restore it (restore option is greyed out). I tried with/without admin privileges.

![image](https://user-images.githubusercontent.com/7317522/94471320-dd1dd300-01c0-11eb-8fde-6e06afd68da2.png)

**Comment by kangyu-california** [comment]
Window position persistency at disk level is designed to be executed manually.
To be specific, user need to capture to disk first, before restore from disk operation can be executed.
Since there is no captured data on disk, the restore from disk option is grayed out.

I feel sorry that you have lost all window position before reboot, but that is not a bug.

**Comment by dhaern** [comment]
"dont remember the captured position" aka I captured it and I can restore until I reboot... once I reboot restore is greyed out but I capture it and tested a few times.

**Comment by kangyu-california** [comment]
It sounds like reboot has deleted the captured db file.

To verify that, please take a look at C:\Users\<your_user_id>\AppData\Local\PersistentWindows, you should have 2 db files.
To open and examine the content of PersistentWindows.1.1.0.0.db, you need to download https://github.com/mbdavid/LiteDB.Studio/releases

If you have captured dual-monitor snapshot before, there should be an entry in that db file.

**Comment by dhaern** [comment]
Looks like only log.db is saving and/or changing modification date.

![image](https://user-images.githubusercontent.com/7317522/94488668-eddb4280-01da-11eb-9daf-2038e9a82120.png)

What content do I need "Run" and check here? $database?

![image](https://user-images.githubusercontent.com/7317522/94488751-1f540e00-01db-11eb-8403-8e70c3c52ec2.png)

**Comment by dhaern** [comment]
I tried again deleting the db files, capturing again and all was working fine, restart and restore option is greyed out again, for whatever reason it's not saving the capture after I restart.

**Comment by kangyu-california** [comment]
This might be caused either by LTSC OS cache policy or missing "flush" operation in PersistentWindows,
The issue does not occur on Windows 10 Pro.

Here is my screen shot
![image](https://user-images.githubusercontent.com/59128756/94490643-7afea700-019b-11eb-87a1-f0368fd669ec.png)

I will figure it out.

**Comment by kangyu-california** [comment]
The issue is fixed by release 4.41

**Comment by dhaern** [comment]
Thanks for the update man but tested 4.41 and bug still not fixed, restore option greyed out after restart and I captured it before restart, db files not updating after I hit capture. Program is not reading/saving it good. Maybe I need install another Windows 10 version but I dont have problems with other software. 

![image](https://user-images.githubusercontent.com/7317522/94860045-68030580-042d-11eb-8909-d8084c789b9e.png)
