### ISSUE TITLE
Unrestored windows saved to incorrect positions

### ISSUE THREAD

**Issue by JohnChristmann** [kangyu-california/PersistentWindows#57]
Persistent Windows saves the positions of all windows, but is only able to restore the positions of windows that are not minimized.  If an application is left minimized (so its position is never restored) and Persistent Windows is triggered a second time, it saves the new incorrect position for that window and attempts to restore to that incorrect position if the window is opened again.  This can easily be seen by opening that application then attempting to move it immediately, and Persistent Windows will move the window back to where it started (the incorrect position that Windows moved it to after the initial display configuration change.)

**Comment by kangyu-california** [comment]
When activate a minimized window, PersistentWindows will restore to the last normal position/size captured prior to minimize operation, as Windows OS lost track of previous normal position especially after toggle monitor on/off or exit from full screen video game.

I would say this is a feature of PW instead of bug

**Comment by JohnChristmann** [comment]
@kangyu-california That is what is supposed to happen, but I'm saying that's not what's actually happening.  A second trigger without restoring the window in between is overwriting the window's original position.  It's very easy to test yourself, simply put a window on your right monitor, minimize it, allow the displays to go into standby twice, then open the window again.  It will not restore to the right monitor as it should, and Persistent Windows will actually try to keep it in its new position on the left monitor if you attempt to move it soon after opening.

**Comment by kangyu-california** [comment]
issue reproduced, thanks for the finding

**Comment by kangyu-california** [comment]
Please try release 5.2

**Comment by JohnChristmann** [comment]
Not sure if this is related but it happened while testing version 5.2:

Application: PersistentWindows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Collections.Generic.HashSet`1+Enumerator[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Ninjacrab.PersistentWindows.Common.PersistentWindowProcessor.BatchFixTopMostWindows()
   at Ninjacrab.PersistentWindows.Common.PersistentWindowProcessor.<Start>b__71_2(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by kangyu-california** [comment]
The crash should have been fixed by release 5.3

**Comment by JohnChristmann** [comment]
Looks like version 5.2 did the trick, thanks!

**Comment by JohnChristmann** [comment]
I think I spoke too soon.  While this update has improved the behavior, Persistent Windows is still sporadically failing to restore minimized windows, with no pattern that I've been able to determine.  Sometimes all my windows restore properly, sometimes only half of them will, but it's different applications each time.

**Comment by kangyu-california** [comment]
I suspect the move to right monitor is not captured by PersistentWindows. which might explain why the minimized window is incorrectly restored to left monitor.

Please allow enough settle time to make sure any window move is captured by PW, usually it takes 3~6 seconds.

put a window on the right monitor, 
**wait for 3 ~ 6 seconds to make sure the move is captured by PW**
minimize it, allow the displays to go into standby twice, 
then open the window again. it should be restored to the right monitor

**Comment by JohnChristmann** [comment]
Even when I make sure to leave windows open for 10+ seconds before minimizing them, this problem still occurs, and still seemingly at random with no pattern that I can discern.  The strange part is that I cannot seem to reproduce this behavior intentionally (IE by setting the standby timer to 1 minute or manually powering off a monitor) - it only happens over longer timeframes during normal PC usage.

**Comment by JohnChristmann** [comment]
Is there some sort of log file I can check to try to figure out what's going on?  In addition to the seemingly random failures to restore certain minimized windows, I've now had two instances where Persistent Windows fails to restore ANY window positions following a display change and I'd really like to try to figure out what's going on.

**Comment by kangyu-california** [comment]
Release 5.5 improved capture latency down to 1 second, this applies to moving window by mouse, minimize, maximize.

In release build, log is provided through Event Viewer, check event id 9990 and 9999 in application log section.

To get full log, you need to build Debug version of PW, and check PersistentWindows.log in the same directory as PersistentWindows.exe

**Comment by JohnChristmann** [comment]
I'm still attempting to investigate this issue as it happens sporadically.  It just happened to me again now (1 out of 4 minimized windows.)  There is no "restore minimized window" log entry for this particular window, but there are for the other three.  As far as I can tell from the log file, my PC switched from 2->1 displays, Persistent Windows started to capture window locations for the new mode which overwrote the position for this window despite it staying minimized, and then after returning 1->2 displays, the new incorrect location was stuck.

**Comment by kangyu-california** [comment]
Please try latest commit,

Take a note of time when 2->1 happens,
and check the if 1->2 is restoring layout to that moment.

![image](https://user-images.githubusercontent.com/59128756/99884843-f30aab80-2be5-11eb-968f-f686461362bd.png)

**Comment by JohnChristmann** [comment]
The restore times all seem to be fine.  I'm still getting occasional failures with no "restore minimized window" event being recorded for that window and the most recent capture for that window being correct.

**Comment by JohnChristmann** [comment]
Ok I just had this occur again, and it appears that I opened the window during the capture process, so the new position was saved rather than the window being restored to its previous position.

**Comment by kangyu-california** [comment]
Big thanks to your effort to reproduce the bug!

**Comment by kangyu-california** [comment]
Please try release 5.7

**Comment by JohnChristmann** [comment]
No change with 5.7.  I also suspect that my previous comment about restoring a window during a capture may have been a coincidence - that's the only time I've noted that timing in the log yet this happens pretty regularly.

**Comment by kangyu-california** [comment]
Still unable to reproduce what you have found.

5.9 release further improves lock mechanism between capture and restore. please try

**Comment by JohnChristmann** [comment]
I'll certainly give that a try.  Thank you for continuing to investigate this.  It tends to happen multiple times a day on my system and I can't find any indication of what's happening in the log files.  I get a valid capture, the window gets ignored due to being minimized, and then when I restore it there's just nothing.  Persistent Windows continues on like I opened a new window.

**Comment by JohnChristmann** [comment]
No change in behavior with 5.9, and still not indication of what's wrong.  Nothing in the log file between the last successful capture and restoring the minimized window, where the minimized window code does not trigger.  The only thing odd I'm noticing is that there's no message with negative window coordinates in the latest instance of this occurring.  It almost looks like the message indicating that the window was minimized was missed?

**Comment by kangyu-california** [comment]
Should have been fixed by release 5.15

**Comment by JohnChristmann** [comment]
No change in version 5.15.  Still seeing the issue multiple times per day, particularly with Mozilla Thunderbird which seems to be about 50/50 whether it will restore or not.

**Comment by kangyu-california** [comment]
I am unable to reproduce issue with thunderbird.
Please attach 2 screen shots before/after restore to validate bug description.

you may also try snapshot feature as a workaround.

**Comment by JohnChristmann** [comment]
An example of before and after a display change while Thunderbird was minimized.  Only took a single attempt this morning.  As mentioned previously I can't find anything in the log file that would indicate a problem, the restore minimized window function simply is not triggered even though the most recent capture of this application is correct.  I will continue monitoring to see if it still happens with any other applications - it may be that this is the only one still exhibiting this problem.
![Screenshot 2021-02-09 084031](https://user-images.githubusercontent.com/17678925/107420768-20bd0d80-6ace-11eb-85d7-6d12fead9950.png)
![Screenshot 2021-02-09 114657](https://user-images.githubusercontent.com/17678925/107420774-21ee3a80-6ace-11eb-84b5-5f0848844fa2.png)

**Comment by kangyu-california** [comment]
Still unable to reproduce your finding. Maybe you need to write a detailed procedure
I have high confidence PW is working fine though.

The thread is too obsessed with minimize/unminimize, 
I would suggest take a break and find some new issue.
