### ISSUE TITLE
Task bar width not being perserved when task bar is vertical

### ISSUE THREAD

**Issue by MFHFozzy** [kangyu-california/PersistentWindows#59]
Config:
3 monitors. 2x27" in landscape orientation @ 2560x1440, side by side. The first is my main monitor, and the second is to its right.
The third monitor is to the mains left and is in portrait orientation.

I have my task bar set vertically on the right side of my right most monitor. Persistent windows restores the taskbar to the correct orientation and position, but its shrinks the width, i think to "default". I have my task bar width normally expanded to about double width.

**Comment by kangyu-california** [comment]
Taskbar is a special window that requires a totally different set of method to recover.
The potential benefit does not justify the required massive effort to fix this.

Closing as wont fix.

**Comment by MFHFozzy** [comment]
How big an effort? Would you consider payment for it?
There is more to this than JUST the task bar. Icon locations get screwed up across the desktops when the taskbar is resized on getting moved to the stored location/monitor. SOMETIMES they get restored after resizing the taskbar to the original size/thickness...sometimes they dont.

If you willing to entertain the idea, email me @ fozzy@foz.com so we can discuss...i dont see how to contact you otherwise through here.

**Comment by kangyu-california** [comment]
Believe or not I could not find sufficient documentation of Win32 API for moving or resizing taskbar window from internet.

In the past, It took me weeks of trial and error to create a hack to simulate mouse move/click in order to drag taskbar around screen, based on [an AHK script](https://stackoverflow.com/questions/2067497/how-to-programmatically-move-windows-taskbar).  And the hack is not 100% reliable.

Now for taskbar resizing, I do not want to repeat the hack procedure again, as Microsoft have the knowledge and resources to improve taskbar implementation anytime, rendering those hacks worthless.

For desktop icon restore, I just closed #68 as wont fix, the reason is that there is a workaround to avoid using that feature, so fixing the feature only provides little marginal benefit for users.

**Comment by kangyu-california** [comment]
The issue is open for volunteer contributor(s)

**Comment by MFHFozzy** [comment]
Ill sweeten the pot: Will provide $500 for a fix (can even put it in an escrow, and sign a contract if desired). 
This utility is the *only* damn thing that works for multi monitors on Win10 on display port.

**Comment by kangyu-california** [comment]
Could you take a screenshot of the vertical taskbar?
On my machine, vertical taskbar with double normal width seems to restore fine.

**Comment by MFHFozzy** [comment]
Sure thing, attached

**Comment by kangyu-california** [comment]
Tentatively fixed in 5.11.

If you are satisfied, appreciate your donation of any amount.
my paypal account is  yukang_email@yahoo.com

Thanks and happy new year!

**Comment by garyd9** [comment]
I'm leaving a comment here to reference something I wrote on #56, but #56 is marked as closed (though it's not actually fixed.)  This is in regards to certain apps not getting restored when the top level (desktop level) window is an invisible control window (as usually happens with skinned apps such as winamp.)  I have a suggested fix for that issue in that issue.

**Comment by MFHFozzy** [comment]
Some how, i missed this 3 days ago! 
Testing now..and happy new year!

**Comment by MFHFozzy** [comment]
Confirmed working! Paypal sent :)

**Comment by kangyu-california** [comment]
@MFHFozzy 
Thanks for the donation.
Feel free to propose more ideas / feature requests, which will be treated with VIP priority.
